-- CRIANDO A DATABASE
CREATE DATABASE dbMercado;

USE dbMercado;

CREATE TABLE tbUsuario(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR (40) NOT NULL,
    Email VARCHAR (50) NOT NULL,
    Senha VARCHAR (255) NOT NULL
);
CREATE TABLE tbProdutos(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR (40) NOT NULL,
    Descricao VARCHAR (255) NOT NULL,
    Preco DECIMAL (10, 2) NOT NULL, 
    Quantidade SMALLINT NOT NULL
);
